name: build

on:
  push:
  pull_request:

jobs:
  xgo:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        goplatform: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: crazy-max/ghaction-xgo@v2
        with:
          xgo_version: latest
          go_version: 1.19
          dest: build
          targets: ${{ matrix.goplatform }}/${{ matrix.goarch }}
          v: true
          x: false
          race: false
          ldflags: -s -w
          buildmode: default
          trimpath: true
          pkg: cmd/sequence_db
      - uses: actions/upload-artifact@v3
        with:
          name: artifact-${{ matrix.goplatform }}-${{ matrix.goarch }}
          path: build
