name: build

on:
  push:
  pull_request:

jobs:
  xgo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get time
        uses: gerred/actions/current-time@master
        id: current-time
      - name: Build
        uses: crazy-max/ghaction-xgo@v2.4.0
        env:
          CGO_ENABLED: 1
          TIME: "${{ steps.current-time.outputs.time }}"
        with:
          xgo_version: latest
          go_version: 1.19
          dest: dist
          prefix: sequence
          targets: linux/amd64,linux/arm-7,linux/arm64
          ldflags: -X main.appCommit=${{ github.sha }} -X main.appDate=${{ env.TIME }}
          pkg: cmd/sequence_db

      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
