# .github/workflows/release.yaml

on:
  release:
    types: [created]

jobs:
  releases:
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    name: Release Go Binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get tag
        uses: olegtarasov/get-tag@v2
        id: tagName

      - name: Get time
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Build (tun)
        uses: crazy-max/ghaction-xgo@v2.0.0
        env:
          TIME: "${{ steps.current-time.outputs.time }}"
        with:
          xgo_version: latest
          go_version: 1.19
          dest: dist
          prefix: sequence
          targets: linux/amd64,inux/arm-7,linux/arm64
          ldflags: -X sequence.Version=${{ env.GIT_TAG_NAME }} -X main.appCommit=${{ github.sha }} -X main.appDate=${{ env.TIME }}
          pkg: cmd/sequence_db

      - name: Generate hashes
        run: |
          cd dist
          for f in $(find . -type f); do
            sha256sum $f >> hashes.txt
          done

      - name: Upload
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./dist/*
