// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Examples         string
	Patterns         string
	PatternsServices string
	Services         string
}{
	Examples:         "Examples",
	Patterns:         "Patterns",
	PatternsServices: "PatternsServices",
	Services:         "Services",
}
